### ISSUE TITLE
reactlibrary/mobilemessaging/ReactChatView.java:65: error: cannot find symbol

### ISSUE THREAD

**Issue by PavanApollo** [infobip/mobile-messaging-react-native-plugin#10]
Hello Team, I have integrated on iOS and it seems that integration is properly setup, however on Android the app is breaking on run time. The error message while running the app is this ` node_modules/infobip-mobile-messaging-react-native-plugin/android/src/main/java/org/infobip/reactlibrary/mobilemessaging/ReactChatView.java:65: error: cannot find symbol`. Please check the screen shot for more clarification.

 
<img width="891" alt="Screenshot 2021-02-04 at 3 11 39 PM" src="https://user-images.githubusercontent.com/78465743/106875314-8ab76a80-66fc-11eb-9911-2d0019326a9d.png">
<img width="923" alt="Screenshot 2021-02-04 at 3 11 52 PM" src="https://user-images.githubusercontent.com/78465743/106875333-91de7880-66fc-11eb-9360-cfe131b5f6ad.png">

I have followed down below steps, still it fails:

 
<img width="896" alt="Screenshot 2021-02-04 at 3 18 52 PM" src="https://user-images.githubusercontent.com/78465743/106875099-4c21b000-66fc-11eb-970b-78edd432fc80.png">

**Configurations:**
Android Studio: 4.1.2
React Native : 0.61.3
mobile-messaging-react-native-plugin: 2.5.0 

Help will be appreciated. @riskpp @tjuric

**Comment by riskpp** [comment]
Hi @PavanApollo, sorry for delayed answer. Please check [2.5.2 version](https://github.com/infobip/mobile-messaging-react-native-plugin/releases/tag/2.5.2), should be fine there.
BR, Olga

**Comment by tjuric** [comment]
I'm closing this task cause we've identified this issue in 2.5.0 version of our library and fixed it in 2.5.2.
