### ISSUE TITLE
MobileMessagingChatImages.car" not found

### ISSUE THREAD

**Issue by phvillegas** [infobip/mobile-messaging-react-native-plugin#11]
Hello Team, I followed the instructions mentioned on README.md file and got the following error:

`error: Resource "/Users/user/Library/Developer/Xcode/DerivedData/App-hababimzkwlhcoddzzjplphyfkci/Build/Products/Debug-iphonesimulator/MobileMessaging/MobileMessaging.framework/MobileMessagingChatImages.car" not found. Run 'pod install' to update the copy resources script.`

### package.json:

```json
"react-native": "0.63.4",
"infobip-mobile-messaging-react-native-plugin": "^2.5.2"
```

## Podfile
```
platform :ios, '10.0'
use_frameworks! :linkage => :static
```

Hope someone can help in integration to iOS

**Comment by phvillegas** [comment]
@riskpp @tjuric Please help me with this.

Thanks!

**Comment by riskpp** [comment]
Hi @phvillegas, MobileMessaging SDK doesn't support static linkage now.
You can try to make following steps: 

1. remove `:linkage => :static`
2. comment out flipper in podfile:
```
  #use_flipper!
  #post_install do |installer|
    #flipper_post_install(installer)
  #end
```
3. make `pod deintegrate`, `pod install`

Or, if you have dependencies which doesn't support dynamic linkage, you can [integrate MobileMessaging plugin manually](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60))

BR, Olga

**Comment by phvillegas** [comment]
Hi @riskpp, thanks for your answer.

I'm going to manually integrate `MobileMessaging` plugin.

**Comment by phvillegas** [comment]
I close this issue.
