### ISSUE TITLE
Error: UNDELIVERABLE_REJECTED_OPERATOR on Production App

### ISSUE THREAD

**Issue by dericksa** [infobip/mobile-messaging-react-native-plugin#13]
When trying to send a push notification (by the infobip portal) to a production app, it shows the following on logs:

```
Undeliverable - Handset errors
Expired pushRegistrationId (code 8001)
Reason: UNDELIVERABLE_REJECTED_OPERATOR
Teste
mar 02, 15:54:40
MadeiraMadeira
Comunicação
Teste
```

But if i try any Sandbox (Like production) it works.

I've attached the Apple Push Services certificate to the production app (It's the right one accordingly to the tutorial). So why when using production to send push notifications, it doesnt work?

**Comment by riskpp** [comment]
Hi @dericksa, may be this article could help you [I-don't-receive-push-notifications](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/I-don't-receive-push-notifications).

BR, Olga
