### ISSUE TITLE
No such module 'MobileMessaging'

### ISSUE THREAD

**Issue by phvillegas** [infobip/mobile-messaging-react-native-plugin#14]
Hello Team.

 I followed the instructions mentioned on [integrate MobileMessaging plugin manually](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60)) and my application works fine.

 Now I want to configure he [**Rich Notifications**](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Notification-Service-Extension-for-Rich-Notifications-and-better-delivery-reporting-on-iOS-10) for iOS and I've got a problem in `NotificationService.swift` file. I followed the instructions in the documentation.

 <img width="1053" alt="Captura de Pantalla 2021-03-12 a la(s) 15 23 58" src="https://user-images.githubusercontent.com/8649643/110984350-c8399400-8349-11eb-88b4-0868c1f91ee8.png">

 Hope someone can help in integration the rich notifications to iOS.
 Thanks!

**Comment by riskpp** [comment]
Hi @phvillegas, we will check it and return with the answer soon.
BR, Olga

**Comment by riskpp** [comment]
Looks like you didn't specified path to `MobileMessaging.framework` in `Framework Search Path` for `MobileMessagingNotificationExtension` target. I updated steps a bit, to make them more clear [Integrating Notification service extension](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60)#integrating-notification-service-extension)

BR, Olga

**Comment by phvillegas** [comment]
Hi @riskpp

I followed the steps mentioned in [Integrating Notification service extension](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60)#integrating-notification-service-extension) and this works for me.
But when setting up rich notifications I get error `No such module 'MobileMessaging'`

![Captura de Pantalla 2021-03-15 a la(s) 09 43 29](https://user-images.githubusercontent.com/8649643/111157151-504fb180-8575-11eb-8246-75516dc48778.png)
![Captura de Pantalla 2021-03-15 a la(s) 09 49 19](https://user-images.githubusercontent.com/8649643/111157175-58a7ec80-8575-11eb-9029-ae17b90fc608.png)
![Captura de Pantalla 2021-03-15 a la(s) 09 50 22](https://user-images.githubusercontent.com/8649643/111157190-5c3b7380-8575-11eb-9d11-b341e017a1d5.png)
![Captura de Pantalla 2021-03-15 a la(s) 09 51 01](https://user-images.githubusercontent.com/8649643/111157199-5e9dcd80-8575-11eb-9047-90a58565ede8.png)
![Captura de Pantalla 2021-03-15 a la(s) 10 01 34](https://user-images.githubusercontent.com/8649643/111157272-75dcbb00-8575-11eb-8a51-8cb8ffdf2aa3.png)

**Comment by phvillegas** [comment]
Hi @riskpp, thanks for your answer.

I followed the steps mentioned in [Integrating Notification service extension](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60)#integrating-notification-service-extension) and this works for me.
But when setting up rich notifications I get error  `No such module 'MobileMessaging'`

![Captura de Pantalla 2021-03-15 a la(s) 09 43 29](https://user-images.githubusercontent.com/8649643/111157151-504fb180-8575-11eb-8246-75516dc48778.png)
![Captura de Pantalla 2021-03-15 a la(s) 09 49 19](https://user-images.githubusercontent.com/8649643/111157175-58a7ec80-8575-11eb-9029-ae17b90fc608.png)
![Captura de Pantalla 2021-03-15 a la(s) 09 50 22](https://user-images.githubusercontent.com/8649643/111157190-5c3b7380-8575-11eb-9d11-b341e017a1d5.png)
![Captura de Pantalla 2021-03-15 a la(s) 09 51 01](https://user-images.githubusercontent.com/8649643/111157199-5e9dcd80-8575-11eb-9047-90a58565ede8.png)
![Captura de Pantalla 2021-03-15 a la(s) 10 10 49](https://user-images.githubusercontent.com/8649643/111158417-c43e8980-8576-11eb-9fcf-01160d07ee4f.png)

**Comment by riskpp** [comment]
@phvillegas 
For `TN` target your setup looks right, but in the targets list you also have `MobileMessagingNotificationExtension` target, looks like `Framework Search Path` in `Build Settings` tab not specified for it. 
Check this target please.

![MMNotificationExtension target](https://user-images.githubusercontent.com/8104718/111158919-9b83b780-85a9-11eb-8c1d-cade10f599ff.png)

BR, Olga

**Comment by phvillegas** [comment]
Hi @riskpp.

The solution you have given me works perfectly, so thank you for that. However, I have another problem: I get all the notifications but I can't visualize the image in each of them.
How could I solve this problem?

Thanks in advance.
Pedro

**Comment by riskpp** [comment]
Hi @phvillegas , could you check [Requirements](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Rich-notifications#requirements)

May be your images from non-https (http) sources? Then make sure your extension allows arbitrary loads from non-secure sources - check  for details [Notification Service Extension Troubleshooting](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Notification-Service-Extension-for-Rich-Notifications-and-better-delivery-reporting-on-iOS-10#troubleshooting)

BR, Olga

**Comment by phvillegas** [comment]
Hi @riskpp, thanks for your help.

I added `MobileMessagingNotificationExtension` **target** to `Podfile` and this worked.

```
...
use_react_native!(:path => config["reactNativePath"])

target 'MobileMessagingNotificationExtension' do
    inherit! :search_paths
  end

...
```

Thanks a lot.
Pedro
