### ISSUE TITLE
The following build commands failed:         Ld /Users/eogie/Library/Developer/Xcode/DerivedData/NativeTest-bvvnjxrhewatpcavpvzfxapqqryd/Build/Products/Debug-iphonesimulator/infobip-mobile-messaging-react-native-plugin/infobip_mobile_messaging_react_native_plugin.framework/infobip_mobile_messaging_react_native_plugin normal (1 failure)

### ISSUE THREAD

**Issue by Aliakwe** [infobip/mobile-messaging-react-native-plugin#15]
I get this error when i run react-native run-ios after pod install when integrating with this package

**Comment by riskpp** [comment]
Hi @Aliakwe, 
could you please try following steps:
1. cd ios
2. pod deintegrate
3. pod install

BR, Olga

**Comment by Aliakwe** [comment]
thanks this solves the issue

**Comment by Aliakwe** [comment]
Hello,

Trust you are well.

So I am getting this error trying to integrate with this package

The following build commands failed:
        Ld /Users/eogie/Library/Developer/Xcode/DerivedData/stowMobile-cxpdjgrsvggoaqfbvogflbxiirfn/Build/Products/Debug-iphonesimulator/RNScreens/RNScreens.framework/RNScreens normal
        MergeSwiftModule normal x86_64

This error occurs after i install the package and edit the pod file and then run react-native run-ios

Hope to get feedback from you soon.

Best regards

From: Olga Koroleva ***@***.***>
Reply to: infobip/mobile-messaging-react-native-plugin ***@***.***>
Date: Monday, 15 March 2021 at 08:50
To: infobip/mobile-messaging-react-native-plugin ***@***.***>
Cc: Emmanuel Ogie ***@***.***>, Mention ***@***.***>
Subject: Re: [infobip/mobile-messaging-react-native-plugin] The following build commands failed: Ld /Users/eogie/Library/Developer/Xcode/DerivedData/NativeTest-bvvnjxrhewatpcavpvzfxapqqryd/Build/Products/Debug-iphonesimulator/infobip-mobile-messaging-re...


Hi @Aliakwe<https://github.com/Aliakwe>,
could you please try following steps:

  1.  cd ios
  2.  pod deintegrate
  3.  pod install

BR, Olga

**Comment by imorakzai** [comment]
> 3\. pod install

The following build commands failed:
        CompileC /Users/ismail/Library/Developer/Xcode/DerivedData/metahub-gxbnqiuonnykhhfwcedxucjcwdpa/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/TimeoutManager.o /Users/ismail/Dropbox/My\ Mac\ (Muhammad’s\ MacBook\ Pro)/Desktop/clones/metahub/ios/Pods/RCT-Folly/folly/io/async/TimeoutManager.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(1 failure)

*it doesn't work 
I tried the following steps but  doesn't work:👇

cd ios
pod deintegrate
pod install

ma'am would you like to guide me through this problem 
thanks

**Comment by riskpp** [comment]
Hi @imorakzai , it looks not related to MobileMessaging plugin, but just in case it could be useful for you, currently usage without `use_frameworks!` is available - [Migration guide](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Migration-guides#migration-from-610-to-620-in-case-you-are-getting-rid-of-use_frameworks-in-the-podfile), you could try without it if not yet

**Comment by shinnthantminn** [comment]
cd ios
pod deintegrate
pod install 

i am use this solution but i got still these error 

2023-04-28 01:25:46.382 xcodebuild[75872:377157] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:60D5A3DA-B8BC-42A6-8814-222D0A2C4E46, OS:16.4, name:iPhone 13 }
{ platform:iOS Simulator, id:60D5A3DA-B8BC-42A6-8814-222D0A2C4E46, OS:16.4, name:iPhone 13 }
** BUILD FAILED **


The following build commands failed:
        Ld /Users/terry/Library/Developer/Xcode/DerivedData/panntheefoundation-bdahmkzhbwzcyydcglfmjckjioex/Build/Products/Debug-iphonesimulator/panntheefoundation.app/panntheefoundation normal (in target 'panntheefoundation' from project 'panntheefoundation')
(1 failure)

**Comment by yao3060** [comment]
> cd ios pod deintegrate pod install
> 
> i am use this solution but i got still these error
> 
> 2023-04-28 01:25:46.382 xcodebuild[75872:377157] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled) --- xcodebuild: WARNING: Using the first of multiple matching destinations: { platform:iOS Simulator, id:60D5A3DA-B8BC-42A6-8814-222D0A2C4E46, OS:16.4, name:iPhone 13 } { platform:iOS Simulator, id:60D5A3DA-B8BC-42A6-8814-222D0A2C4E46, OS:16.4, name:iPhone 13 } ** BUILD FAILED **
> 
> The following build commands failed: Ld /Users/terry/Library/Developer/Xcode/DerivedData/panntheefoundation-bdahmkzhbwzcyydcglfmjckjioex/Build/Products/Debug-iphonesimulator/panntheefoundation.app/panntheefoundation normal (in target 'panntheefoundation' from project 'panntheefoundation') (1 failure)

me too

**Comment by riskpp** [comment]
Hello @yao3060 , @shinnthantminn,
Are you sure that you provided full log? From what's provided not really clear what exactly failed.
For faster investigation we need version of RN you are using and your Podfile. Also please try to reproduce it using our [example application](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/How-to-start-Example-app)

**Comment by RsnDev** [comment]
** BUILD FAILED **


The following build commands failed:
	ProcessInfoPlistFile /Users/roushangupta/Library/Developer/Xcode/DerivedData/sudo-czaxeiyvvfzgyfebgbthgqqkkttp/Build/Products/Debug-iphonesimulator/sudo.app/Info.plist /Users/roushangupta/Desktop/project/sudo-merge/ios/sudo/Info.plist (in target 'sudo' from project 'sudo')
(1 failure)

info Run CLI with --verbose flag for more details.
roushangupta@Roushans-Air sudo-merge %

**Comment by slav-getov** [comment]
@tjuric 
Hello and thank you for your reply, appreciate it. I am getting lots of errors and so far everything has been resolved except:

[!] Invalid `Podfile` file: cannot load such file -- /Users/preslavgetov/Documents/TestOne/das-mxp-mobile-experience-onboarding/node_modules/@react-native-community/cli-platform-ios/native_modules.

 #  from /Users/preslavgetov/Documents/TestOne/das-mxp-mobile-experience-onboarding/ios/Podfile:2
 #  -------------------------------------------
 #  require_relative '../node_modules/react-native/scripts/react_native_pods'
 >  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #  
 #  -------------------------------------------

I have no idea what is happening here. 
"react-native": "0.68.1",

and you also wanted my Podfile:

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'experience' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'experienceTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

To confirm cocoapods do I need to do cocoapods -v? Does the install! cocoa pods mean that I do not have it installed correctly?

Any advice is appreciated!
