### ISSUE TITLE
(Manual plugin Integration) Native module cannot be null 

### ISSUE THREAD

**Issue by dericksa** [infobip/mobile-messaging-react-native-plugin#16]
When using the manual plugin integration for iOS i get this error importing:
`import { mobileMessaging } from 'infobip-mobile-messaging-react-native-plugin';`

And trying to set mobileMessaging.init()

MobileMessaging.frameworks is already on frameworks, libraries, etc and Link Binary with Libraries

**Comment by riskpp** [comment]
Hi @dericksa , could you try following steps:
https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60)#notice

BR, Olga

**Comment by dericksa** [comment]
> Hi @dericksa , could you try following steps:
> https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60)#notice
> 
> BR, Olga

Hello @riskpp, i have followed these steps, the error start appearing after it.

**Comment by dericksa** [comment]
Log:
```
2021-03-18 10:39:40.075 [error][tid:com.facebook.react.JavaScript] Invariant Violation: Native module cannot be null.
2021-03-18 10:39:40.089 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: Native module cannot be null.
```

The problem is with `import { mobileMessaging } from 'infobip-mobile-messaging-react-native-plugin';
`

**Comment by riskpp** [comment]
Could you please try to build your project in Xcode? Which react-native version are you using?

**Comment by dericksa** [comment]
> Could you please try to build your project in Xcode? Which react-native version are you using?

I'm using xcode to build the project. RN 62.2
