### ISSUE TITLE
In app notifications

### ISSUE THREAD

**Issue by phvillegas** [infobip/mobile-messaging-react-native-plugin#17]
Hi Team,

How can I customize the button text color?

| | |
|--------|----------| 
| ![android](https://github.com/infobip/mobile-messaging-sdk-android/wiki/images/InAppDefaultActionsAndroid.png?raw=true)| ![ios](https://github.com/infobip/mobile-messaging-sdk-ios/wiki/Images/InAppDefaultActionsIos.png?raw=true)

**Comment by tjuric** [comment]
Hi @phvillegas,
Button text color on in-app dialog is managed by style attribute `colorAccent`. Could you try applying following style as stated in [native Android SDK docs](https://github.com/infobip/mobile-messaging-sdk-android/wiki/In-app-notifications#customize-button-text-color)? 
```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
    <item name="colorAccent">#0000FF</item>
</style>
```

BR,
Tereza

**Comment by phvillegas** [comment]
Hi @tjuric, thank you for your support.

Do you know if in iOS I can customize the color of the button text? or  Can I disable `In app notifications` from JavaScript?

Thanks!

**Comment by riskpp** [comment]
Hi @phvillegas!

For iOS In-app notification button text color is taken from app global tint color. You can customize it with `MMInteractiveMessageAlertSettings.tintColor` parameter in AppDelegate, such as:
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    MMInteractiveMessageAlertSettings.tintColor = UIColor.blue
    return true
}
```

BR, Olga

**Comment by phvillegas** [comment]
Hi @riskpp, @tjuric.

Thank you for your support

**Comment by Pxinxs365** [comment]
Hi
How can I customize the title and description colors?
