### ISSUE TITLE
Building issue on Xcode 12.5

### ISSUE THREAD

**Issue by ARazaAnjum** [infobip/mobile-messaging-react-native-plugin#21]
Hi,

On Xcode 12.4 we just saw the warnings, but now on the new Xcode 12.5 they have become errors.I think that this should be taken care of now. Not sure how much I can just remove these attributes.

Error:

ios/Pods/MobileMessaging/Classes/Vendor/CryptoSwift/Generics.swift:39:28: 'exported: true' has no effect in '_specialize' attribute'_specialize' attribute
@_specialize(exported: true, where T == Int) 'exported: true' has no effect in '_specialize' attribute
@_specialize(exported: true, where T == UInt)'exported: true' has no effect in '_specialize' attribute
@_specialize(exported: true, where T == UInt8) 'exported: true' has no effect in '_specialize' attribute
@_specialize(exported: true, where T == UInt16) 'exported: true' has no effect in '_specialize' attribute
@_specialize(exported: true, where T == UInt32) 'exported: true' has no effect in '_specialize' attribute
@_specialize(exported: true, where T == UInt64) 'exported: true' has no effect in '_specialize' attribute
                           ^
ios/Pods/MobileMessaging/Classes/Vendor/CryptoSwift/UInt32+Extension.swift:32:29: 'exported: true' has no effect in '_specialize' attribute
@_specialize(exported: true, where T == ArraySlice<UInt8>)

Versions:

MobileMessaging SDK version: 3.0.3
Xcode version: 12.5
Cocoapods version: 1.10.1

**Comment by riskpp** [comment]
Hi @ARazaAnjum, thank you for reporting it, actually changes already done on iOS SDK and we will update plugin today!

BR, Olga

**Comment by riskpp** [comment]
@ARazaAnjum, we've released [3.1.0 version](https://github.com/infobip/mobile-messaging-react-native-plugin/releases/tag/3.1.0) with Xcode 12.5 support.

BR, Olga

**Comment by riskpp** [comment]
Closing it, seems it's sloved.
