### ISSUE TITLE
We suddenly stopped receiving notifications on our iOS devices

### ISSUE THREAD

**Issue by phvillegas** [infobip/mobile-messaging-react-native-plugin#25]
Hi team,

A month ago, we received notifications on our iOS devices, but now the **Infobip** service is not working on the mentioned platform. I checked that those devices had a pushRegistrationId, and when we searched for those IDs in the **Infobip** database (by logging in [https://portal.infobip.com/login/](https://portal.infobip.com/login/)) and I couldn’t find those IDs. I also waited for several hours in order to check if there was some kind of delay in the database, but that was not the case. On the other hand, some iOS users are receiving some notifications but not all of them. An example of this is an iOS developer that we have in the team that has a pushRegistrationId that, according to **Infobip**, says that the last contact was ‘Never’. In this case, for example, is a person with an iPhone that works with it 50 hours per week with the App installed and working.

How can this be fixed?

Best regards and waiting for your comments.
Thanks!

**Comment by riskpp** [comment]
Hi @phvillegas,

Could you please send this question with the list of pushRegistrationIds affected to `support@infobip.com` along with your [Infobip Portal](https://portal.infobip.com/) login?

BR, Olga
