### ISSUE TITLE
No such module 'MobileMessaging' in the version 4.0.0

### ISSUE THREAD

**Issue by lrusso** [infobip/mobile-messaging-react-native-plugin#28]
Hello, I'm currently using the 3.1.0 version and when trying to update to the latest version, I'm getting a "No such module 'MobileMessaging'".

In the 3.1.0 version I added to the FRAMEWORK_SEARCH_PATHS to following path:

$(SRCROOT)/../node_modules/infobip-mobile-messaging-react-native-plugin/ios/Carthage/Build/iOS/

But in the 4.0.0 version that path does not exist.

Best regards and waiting for your comments,
Leonardo

**Comment by kas-kad** [comment]
Hello, please provide information about your environment as complete as possible.

**Comment by lrusso** [comment]
In the package.json we have a `"postinstall": "cd node_modules/infobip-mobile-messaging-react-native-plugin && npm run mm_build"` that it's required in order to the Infobip plugin to work with the iOS App.

In the 3.1.0 version I added to the FRAMEWORK_SEARCH_PATHS to following path:

`$(SRCROOT)/../node_modules/infobip-mobile-messaging-react-native-plugin/ios/Carthage/Build/iOS/`

<img width="896" alt="Ver310" src="https://user-images.githubusercontent.com/11498901/127203820-686d1044-3ffb-481a-9eb5-c4700b024490.png">

But in the 4.0.0, the iOS folder is not there.

<img width="897" alt="Ver400" src="https://user-images.githubusercontent.com/11498901/127203927-3b624de1-b265-4b22-aa25-a48be15fabef.png">

Because of this, I got the "No such module 'MobileMessaging'" error message in the 4.0.0 version.

**Comment by kas-kad** [comment]
What is your Xcode version?

**Comment by lrusso** [comment]
12.4

**Comment by kas-kad** [comment]
Minumun required Xcode version for 4.0.0 is 12.5 ([Readme](https://github.com/infobip/mobile-messaging-react-native-plugin#readme))

**Comment by lrusso** [comment]
I just updated to xcode 12.5.1 and the issue remains:

<img width="852" alt="error" src="https://user-images.githubusercontent.com/11498901/127336009-bffa2217-781a-4882-a7ad-10ad209d472c.png">

And the Carthage folder doesn't have the Build/iOS framework folder like the 3.x version:

<img width="896" alt="folder" src="https://user-images.githubusercontent.com/11498901/127337982-a6b50804-6c26-49d8-8036-cebc3d8cbd8b.png">

**Comment by kas-kad** [comment]
What is your Carthage version?

**Comment by lrusso** [comment]
0.37.0

**Comment by kas-kad** [comment]
does it help if you change `FRAMEWORK_SEARCH_PATHS`  to `$(SRCROOT)/../node_modules/infobip-mobile-messaging-react-native-plugin/ios/Carthage/Build`?

**Comment by kas-kad** [comment]
>I just updated to xcode 12.5.1 and the issue remains:
did you try to reinstall the plugin after updating to newer Xcode?

**Comment by lrusso** [comment]
I just tried both suggestions and the issue remains.

**Comment by kas-kad** [comment]
What is your React Native version?

**Comment by kas-kad** [comment]
Have you followed this [guide](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60)) ?

**Comment by lrusso** [comment]
Yes, but it didn't work for me. My solution was to use `$(SRCROOT)/../node_modules/infobip-mobile-messaging-react-native-plugin/ios/Carthage/Build/MobileMessaging.xcframework` and 'Do Not Embed' in the MobileMessaging framework.
