### ISSUE TITLE
How can use this library in IOS  without adding use_framework!

### ISSUE THREAD

**Issue by alamataffan** [infobip/mobile-messaging-react-native-plugin#3]
My other react natives libraries are getting conflict if i use use_framework!
is there any  work around without using use_framework! in pod file ?

**Comment by riskpp** [comment]
Hi @alamataffan could you please try this approach [Manual plugin integration for iOS (in case your dependencies do not support `use_frameworks!`)](Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-`use_frameworks!`))

**Comment by riskpp** [comment]
Hello @alamataffan do you have any issues with this approach? or I can close this issue?
