### ISSUE TITLE
App Killed : Notification Tapped Not Detected.

### ISSUE THREAD

**Issue by Rohit-Surawat** [infobip/mobile-messaging-react-native-plugin#34]
Hi All,

May i know how to detect notification tap event if app is killed.

Detail Scenario: Suppose a new notification that is right now in notification tray is tapped how to detect that and store notification data in the application state suppose redux for deep linking.

Please help us on this as we are facing this issue
infobip lib version :2.2.0

Thanks & Regards
Rohit

**Comment by kostap13** [comment]
Hi @Rohit-Surawat 

As I understood it related to this issue: https://github.com/infobip/mobile-messaging-react-native-plugin/issues/33

Let's discuss this issue at related thread

**Comment by riskpp** [comment]
Hello @Rohit-Surawat,
- At first better to update plugin to the latest version, we've implemented some bug fixes for receiving notification tapped event.
- Use "notificationTapped" library event - [Library Events](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Library-events)

**Comment by riskpp** [comment]
Was fixed in 5.0.1 version
