### ISSUE TITLE
App crash on mobile-messaging initialization

### ISSUE THREAD

**Issue by vokecodes** [infobip/mobile-messaging-react-native-plugin#37]
After creating the widget on the dashboard and following the infobip-mobile-messaging-react-native-plugin installation guide, the Android app fails to build with this error
```
Execution failed for task ':app:mergeDebugResources'.
> [string/google_app_id] /android/app/src/main/res/values/strings.xml	[string/google_app_id] /android/app/build/generated/res/google-services/debug/values/values.xml: Error: Duplicate resources
```
If I should remove this line of code below in `/android/app/src/main/res/values/strings.xml ` the app builds successfully.
`<string name="google_app_id">your google app id</string>`

We have Firebase set up in the app with the google-services.json file.
When I get to build the app successfully for development, after initialization configuration,  the app crashes,

**Comment by vokecodes** [comment]
Hi @kostap13 @tjuric, 

What we did was to add key/values from google-services.json to resource strings (strings.xml) and removed this line `apply plugin: 'com.google.gms.google-services'` from the build.gradle file. 

It works!

Thanks

**Comment by ahadtechcarrot** [comment]
> 

Hi @vokecodes if I remove `apply plugin: 'com.google.gms.google-services'` then I am getting a different error. Can you please elaborate on the process of setting up infobip in android?

**Comment by ahadtechcarrot** [comment]
> 

@vokecodes Thank you for your response. Can you let me know the keys which will be used from google-services.json in these strings element in the place of *** as  I am not aware of all the keys in the above answer?

**Comment by riskpp** [comment]
Hi @ahadtechcarrot  you can find this information here - https://developers.google.com/android/guides/google-services-plugin

**Comment by ahadtechcarrot** [comment]
Thank you @riskpp but I am facing errors in both the scenarios now : 

Scenario 1 : removing `apply plugin: 'com.google.gms.google-services'` and adding all the values in strings.xml I am getting the error message : 

```
> Task :app:fabricGenerateResourcesStagingGoogleDebug FAILED
ERROR - Crashlytics Developer Tools error.
java.lang.IllegalArgumentException: Crashlytics found an invalid API key: null. 
```

Scenarios 2 : Using `apply plugin: 'com.google.gms.google-services'`

`Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/~~HqJrbxlqvpKu-fCiGQ_E2Q==/com.reelCinema.Screens.stage-FIAC9pxSrE844PRXDZOPtg==/base.apk"],nativeLibraryDirectories=[/data/app/~~HqJrbxlqvpKu-fCiGQ_E2Q==/com.reelCinema.Screens.stage-FIAC9pxSrE844PRXDZOPtg==/lib/x86, /data/app/~~HqJrbxlqvpKu-fCiGQ_E2Q==/com.reelCinema.Screens.stage-FIAC9pxSrE844PRXDZOPtg==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]`

@riskpp @vokecodes can provide any help regarding this?

**Comment by riskpp** [comment]
@ahadtechcarrot could you pls check compileSdkVersion, targetSdkVersion on your build.gradle, and which version of `com.google.firebase:firebase-messaging` are you using? 
I could only guess that you probably have compileSdkVersion or targetSdkVersion = 31 or using newer version of `com.google.firebase:firebase-messaging`, installed by some other plugin.
If it's the case: we've updated Android SDK to support Android 12, but for plugins this task isn't yet done.

**Comment by ahadtechcarrot** [comment]
@riskpp I am using react-native third party plugins for firebase : 

```
    "@react-native-firebase/analytics": "^12.0.0",
    "@react-native-firebase/app": "^12.0.0",
    "@react-native-firebase/auth": "^12.0.0",
    "@react-native-firebase/crashlytics": "^12.0.0",
```
I have no setup done for firebase-messaging as there is no mention of that in your documentation and the above firebase libraries we are using already before this infobip setup. Also, please find my configurations in build.gradle file : 

```
        buildToolsVersion = "29.0.3" 
        minSdkVersion = 21  
        compileSdkVersion = 30  
        targetSdkVersion = 30   
        supportLibVersion = "28.0.0"    
        playServicesVersion = "15.0.1"
        androidMapsUtilsVersion = "0.5+"    
        googlePlayServicesAuthVersion = "16.0.1"   
```

**Comment by ahadtechcarrot** [comment]
@riskpp please let me know if I am missing out on something for Android for Version 5.0.1. As per the documentation in GitHub, I have only written the key/value pairs in the strings.xml file and updated the .bash_rc file.

**Comment by tjuric** [comment]
Just to have a follow-up here as well, 
@ahadtechcarrot your issue has been moved to a new thread https://github.com/infobip/mobile-messaging-react-native-plugin/issues/39 and solved.
