### ISSUE TITLE
TypeError: Cannot read property 'deleteAll' of undefined

### ISSUE THREAD

**Issue by vokecodes** [infobip/mobile-messaging-react-native-plugin#43]
Below code results in a promise rejection with the error `TypeError: Cannot read property 'deleteAll' of undefined`

```
import { mobileMessaging } from 'infobip-mobile-messaging-react-native-plugin';
mobileMessaging.defaultMessageStorage().deleteAll(() => {
       console.log('Deleted all messages');
 });
```

**Comment by vokecodes** [comment]
I added this line of code to the initialization `defaultMessageStorage: true`. I didn't get the error but messages didn't get deleted.

**Comment by riskpp** [comment]
Hi @vokecodes, I suppose plugin version you are using is 5.0.1? Could you may be share logs and which platform are you testing?

**Comment by vokecodes** [comment]
@riskpp Yes, 5.0.1. Testing on Android. Shared logs via mail.

**Comment by riskpp** [comment]
Hi @vokecodes, from my side everything looks fine.
You can check may be you've missed something from the [Default message storage doc](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Message-storage#default-message-storage).

 I've just implemented following in [Example app](https://github.com/infobip/mobile-messaging-react-native-plugin/tree/master/Example)
Don't forget to add `defaultMessageStorage: true` to the config.

```js
//components/homeScreen.js
//Implemented methods for default storage
class HomeScreen extends React.Component {
...
  deleteAll() {
    mobileMessaging.defaultMessageStorage().deleteAll(() => {
      console.log('Delete all');
    });
  }

  findAll() {
    mobileMessaging.defaultMessageStorage().findAll((messages) => {
      console.log('Find All, Messages: ' + JSON.stringify(messages));
    });
  }
 }
 ...
 //Added buttons to the home screen
 render() {
    return (
      <View style={styles.infoView}>
      ...
        <Button
            title="Delete All on default storage"
            onPress={() => this.deleteAll()}
        />
        <Button
            title="Find all messages from default storage"
            onPress={() => this.findAll()}
        />
      </View>
    );
}
```

Resulting logs:
```
 LOG  Event: ["messageReceived",{"body":"Text1","title":"Title1"}]
 LOG  Event: ["messageReceived",{"body":"Text2", "title":"Title2"}]
 LOG  Find All, Messages: [{"body":"Text1","title":"Title1"},{"body":"Text2","title":"Title2"}]
 LOG  Delete all
 LOG  Find All, Messages: []

```

**Comment by riskpp** [comment]
Check the format of the number it should correspond to https://en.wikipedia.org/wiki/E.164, more information also [here](https://www.infobip.com/docs/sms/deliverability#number-formatting)

**Comment by vokecodes** [comment]
Yes, I formatted it 
` Invalid phone number: 270999999913 (number does not have valid country/network prefix)`

**Comment by riskpp** [comment]
Hi @vokecodes, could you check the number one more time, it doesn't look valid per this rules - https://en.wikipedia.org/wiki/E.164

**Comment by vokecodes** [comment]
I used a random test number but need to use a real phone number.
