### ISSUE TITLE
The following build commands failed:

### ISSUE THREAD

**Issue by bruhmamba** [infobip/mobile-messaging-react-native-plugin#51]
CpResource /Users/xxx/Downloads/app/src/assets/fonts/reost-semibold.otf /Users/xxx/Library/Developer/Xcode/DerivedData/travel-dftjgjmdydcfaihhcfrbcmcfwzzp/Build/Products/Debug-iphonesimulator/travel.app/reost-semibold.otf
        CpResource /Users/xxx/Downloads/react-native-travel-app-main/src/assets/fonts/reost-medium.otf /Users/xxx/Library/Developer/Xcode/DerivedData/travel-dftjgjmdydcfaihhcfrbcmcfwzzp/Build/Products/Debug-iphonesimulator/travel.app/reost-medium.otf
        CpResource /Users/xxx/Downloads/react-native-travel-app-main/src/assets/fonts/reost-light.otf /Users/xxx/Library/Developer/Xcode/DerivedData/travel-dftjgjmdydcfaihhcfrbcmcfwzzp/Build/Products/Debug-iphonesimulator/travel.app/reost-light.otf
(3 failures)

**Comment by riskpp** [comment]
Hi @bruhmamba, looks like it's some files with custom fonts. It's not connected to the mobile-messaging plugin, it doesn't use any files like this.
