### ISSUE TITLE
react native ios manual plugin issue

### ISSUE THREAD

**Issue by tarunasharma089** [infobip/mobile-messaging-react-native-plugin#6]
It builds fine in local system but fails in dev ops when built through CI, error attached. Its probably because in manual integration we use npm run mm_build and Carthage which is not there in azure. Please help how can we do this manual integration in azure.
<img width="1016" alt="Screenshot 2020-09-08 at 9 24 18 AM" src="https://user-images.githubusercontent.com/26599494/92436635-31cbc080-f1b6-11ea-9b0e-ec7b59c7c03b.png">

**Comment by riskpp** [comment]
Hi @tarunasharma089, thank you for your question.

Could you please try following solution:
1. build `MobileMessaging.framework` locally as described in [Manual integration - step 3 (Build MobileMessaging.framework)](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60)#manual-integration-steps). 
2. copy `MobileMessaging.framework` to project you are trying to build in CI environment. 
3. Perform 4,5,6 steps of [Manual integration (Build MobileMessaging.framework)](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/Manual-plugin-integration-for-iOS-(in-case-your-dependencies-do-not-support-%60use_frameworks!%60)#manual-integration-steps) according to path to `MobileMessaging.framework` in your project.
