### ISSUE TITLE
Pods completion on Xcode15

### ISSUE THREAD

**Issue by GennadySX** [infobip/mobile-messaging-react-native-plugin#64]
The issue appears as like below on Operation class 
```
Property 'completionBlock' with type '(() -> Void)?' cannot override a property with type '(@Sendable () -> Void)?'
```

**Comment by jorgerojas26** [comment]
Same issue here

**Comment by riskpp** [comment]
Hello @GennadySX, @jorgerojas26 which version of the plugin are you using? update to the latest should help

**Comment by GennadySX** [comment]
> Hello @GennadySX, @jorgerojas26 which version of the plugin are you using? update to the latest should help
```
    "infobip-mobile-messaging-react-native-plugin": "^8.3.0",
```

**Comment by riskpp** [comment]
Yes it's not the latest version, update to the latest should help https://github.com/infobip/mobile-messaging-react-native-plugin/releases/tag/8.4.0

**Comment by GennadySX** [comment]
> Yes it's not the latest version, update to the latest should help https://github.com/infobip/mobile-messaging-react-native-plugin/releases/tag/8.4.0

but v8.4.0 is not published yet on npm

**Comment by riskpp** [comment]
Hm, I see it there https://www.npmjs.com/package/infobip-mobile-messaging-react-native-plugin/v/8.4.0

**Comment by GennadySX** [comment]
> Hm, I see it there https://www.npmjs.com/package/infobip-mobile-messaging-react-native-plugin/v/8.4.0

oh, sorry
I see now)
