### ISSUE TITLE
Push notifications conflicts

### ISSUE THREAD

**Issue by GennadySX** [infobip/mobile-messaging-react-native-plugin#67]
Hi!
I encountered a notification problem (notifee) if infobip is installed. Now I can’t launch local push notifications because they don’t appear, or rather end up in infobip. Is it possible to make it so that there are exceptions?

thanks in advance

**Comment by riskpp** [comment]
Hello @GennadySX, sorry for the late response, we've missed your question somehow. If it's still relevant could you provide more details please, which version are you using, how are you launching the local push notification and have you tried to reproduce the issue with the [Example application](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/How-to-start-Example-app)

**Comment by riskpp** [comment]
Closing the task due to inactivity, feel free to reopen if needed.
