### ISSUE TITLE
hide notification in foreground

### ISSUE THREAD

**Issue by montheraljodeh** [infobip/mobile-messaging-react-native-plugin#68]
I want to hide popup fcmmessage when app is open how to handle it in reactnative both (android and iOS)
<img width="202" alt="Screenshot 2024-02-05 at 11 25 07 PM" src="https://github.com/infobip/mobile-messaging-react-native-plugin/assets/66224452/65090add-8b19-4d8a-8e77-254e77964553">

**Comment by riskpp** [comment]
Hello @montheraljodeh, could you please provide more information:
- what is the use-case
- which popup do you mean?
- mobileMessaging plugin shouldn't show the in-app notification in case of "inApp":false, do you have any custom implementation or may be other plugin which may show the message?
- may be you can share the screenshot of the message you receive?

**Comment by montheraljodeh** [comment]
I meant the message this alert message (popup ) but I don't want this popup or alert when app is open  not foreground
<img width="202" alt="Screenshot 2024-02-05 at 11 25 07 PM" src="https://github.com/infobip/mobile-messaging-react-native-plugin/assets/66224452/ca7ec8f0-a280-4730-b60d-37797aa13ce2"> 

I want just in the notification in background
<img width="280" alt="Screenshot 2024-02-06 at 6 04 15 PM" src="https://github.com/infobip/mobile-messaging-react-native-plugin/assets/66224452/10def77e-9eb9-4c25-96e4-142368434f72">

we have event when press specific categorey I send the infobip the event by using this one       mobileMessaging.submitEvent(event2)
 I need just show notification in background  same like this
<img width="280" alt="Screenshot 2024-02-06 at 6 04 15 PM" src="https://github.com/infobip/mobile-messaging-react-native-plugin/assets/66224452/10def77e-9eb9-4c25-96e4-142368434f72">

 not when app is open  I want to prevent it 
<img width="202" alt="Screenshot 2024-02-05 at 11 25 07 PM" src="https://github.com/infobip/mobile-messaging-react-native-plugin/assets/66224452/ca7ec8f0-a280-4730-b60d-37797aa13ce2"> 

I checked the inapp is false

we don't have any plugin just we have infobip

**Comment by riskpp** [comment]
Closing the issue, because the problem was resolved. Problem was connected with usage of another push provider which was showing this message.
