### ISSUE TITLE
[ITMS-91053: Missing API declaration] Apple issue review

### ISSUE THREAD

**Issue by Thaimay** [infobip/mobile-messaging-react-native-plugin#69]
I using "infobip-mobile-messaging-react-native-plugin": "^9.1.0" when i upload on testflight. I get response mail like image below. How can i fix it?
<img width="913" alt="Ảnh màn hình 2024-04-17 lúc 15 22 09" src="https://github.com/infobip/mobile-messaging-react-native-plugin/assets/11836057/dbf118fd-de15-43d2-bb5d-4eed70ca3f86">

**Comment by riskpp** [comment]
Hi @Thaimay, 

This is the information e-mail saying that starting from the 1st of May you won't be able to upload the application without the [privacy manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) and we are going to release the update of the plugin soon.
We'll inform you additionally on this thread about this plugin release.

**Comment by Thaimay** [comment]
Thanks @riskpp for your response. If i use an old version, How do i solve this problem without upgrade latest version?

**Comment by riskpp** [comment]
Hi @Thaimay, in the [new 11.1.1 version of the plugin](https://github.com/infobip/mobile-messaging-react-native-plugin/releases/tag/11.1.1) we've added the privacy manifest file for the iOS SDK.

Also Apple requires from you to describe the reason for sharing your user's identity data. Before doing personalisation of your user with actual identity values (such as phone number, email address, name, etc.), remember to include the privacy category affected, as well as the purpose for the sharing, within your PrivacyInfo file, as described in the [official documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests).
You may check how it's done [in the example app](https://github.com/infobip/mobile-messaging-sdk-ios/blob/master/ChatExample/MobileChatExample/PrivacyInfo.xcprivacy).

**Comment by Thaimay** [comment]
Thanks, @riskpp
