### ISSUE TITLE
android proguard issue

### ISSUE THREAD

**Issue by tarunasharma089** [infobip/mobile-messaging-react-native-plugin#7]
Hi please share the rules for proguard

**Comment by tjuric** [comment]
Hi @tarunasharma089,

Sorry for the delayed response. We've released version of SDK [2.1.2](https://github.com/infobip/mobile-messaging-react-native-plugin/releases/tag/2.1.2) that contains Proguard rules for our RN SDK. They should be merged with yours. In case they are not, rules are the following:
`-keep class org.infobip.reactlibrary.mobilemessaging.Configuration* { *; }
-keep class org.infobip.reactlibrary.mobilemessaging.CacheManager* { *; }`

You can check it also here https://github.com/infobip/mobile-messaging-react-native-plugin/blob/master/android/proguard-rules.pro.

BR,
Tereza
