### ISSUE TITLE
Push Notification on iOS Devices Not Received

### ISSUE THREAD

**Issue by moustafadevrn** [infobip/mobile-messaging-react-native-plugin#70]
Push notifications are not being received on iOS devices, although they are successfully received on Android devices. This is despite the profiles in the persons section and pushRegID being set up correctly.

**Steps to Reproduce:**
1. Ensure the profiles in the persons section and pushRegID are set up correctly.
2. Send a push notification to an iOS device.
3. Observe that the notification is not received on the iOS device.

**Expected Outcome:**
The push notification should be received on iOS devices, as it is on Android devices.

**Actual Outcome:**
Push notifications are not received on iOS devices.

we are using version 11 of the Infobip React Native SDK .

**Comment by fortesdev** [comment]
Hi Moustafa, 

the environment in the app (in the device) and the setup in Infobip side need to match. 
Please make sure to target a sandbox application/certificate when deploying your app through Xcode, and a production one when distributing in appstore/testflight, as explained here https://github.com/infobip/mobile-messaging-sdk-ios/wiki/I-don't-receive-push-notifications

Please let us know if a change in the p12 environment helps.
