### ISSUE TITLE
Build iOS fail

### ISSUE THREAD

**Issue by Thaimay** [infobip/mobile-messaging-react-native-plugin#75]
We got this error below when build iOS, please help me check it, i can not find any information for this error log. Thank you.

<img width="678" alt="image-capture" src="https://github.com/infobip/mobile-messaging-react-native-plugin/assets/11836057/6f103b5e-5183-4e5b-bf11-42e7df99ef4d">

We already have the latest sdk from https://www.portsip.com/download-portsip-voip-sdk

**Comment by fortesdev** [comment]
Hi @Thaimay, I think those errors are not related to our SDK.

But you can probably skip that portsip SDK and [integrate voip in our platform](https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/webrtc-calls-and-ui).

Cheers.

**Comment by Thaimay** [comment]
Thanks @fortesdev
