### ISSUE TITLE
Module 'MobileMessaging' not found

### ISSUE THREAD

**Issue by PavanApollo** [infobip/mobile-messaging-react-native-plugin#9]
Hello Team, I have installed `mobile-messaging-react-native-plugin` on the app and followed the instructions mentioned on Readme file, however it is throwing `Module 'MobileMessaging' not found` error even after doing pod install after npm installation. Hope someone can help in integration to iOS. @riskpp @tjuric

**Comment by tjuric** [comment]
Hi @PavanApollo,
Could you try to run our Example application first? Instructions: https://github.com/infobip/mobile-messaging-react-native-plugin/wiki/How-to-start-Example-app

**Comment by PavanApollo** [comment]
Hi @tjuric 
For the example app, we needed to provide our own APNS and FCM so we can upload it on Infobip profile and get back the application code !?
